module ddsmetadata {
  module msg {
    typedef int64 int64__5[5];
    struct DDSMetaData {
      int64 nd;

      int64 type;

      int64 elsize;

      int64 total_size;

      int64__5 dims;

      int64__5 strides;

      sequence<uint8> mdata;
    };
  };
};
