SCRIPTPATH=$(cd `dirname -- $BASH_SOURCE` && pwd)
export MSG_LOG_PATH="${SCRIPTPATH}/log"
mkdir -p $MSG_LOG_PATH
export PYTHONPATH="${SCRIPTPATH}/build:${SCRIPTPATH}:$PYTHONPATH"
export LD_LIBRARY_PATH="${SCRIPTPATH}/build:${SCRIPTPATH}:$LD_LIBRARY_PATH"
